# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "corser-2.0.1" = {
      name = "corser";
      packageName = "corser";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/corser/-/corser-2.0.1.tgz";
        sha1 = "8eda252ecaab5840dcd975ceb90d9370c819ff87";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "ecstatic-3.2.1" = {
      name = "ecstatic";
      packageName = "ecstatic";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecstatic/-/ecstatic-3.2.1.tgz";
        sha512 = "BAdHx9LOCG1fwxY8MIydUBskl8UUQrYeC3WE14FA1DPlBzqoG1aOgEkypcSpmiiel8RAj8gW1s40RrclfrpGUg==";
      };
    };
    "eventemitter3-3.1.0" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.0.tgz";
        sha512 = "ivIvhpq/Y0uSjcHDcOIccjmYjGLcP09MFGE7ysAwkAvkXfpZlC985pH2/ui64DKazbTW/4kN3yqozUxlXzI6cA==";
      };
    };
    "follow-redirects-1.5.1" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.5.1.tgz";
        sha512 = "v9GI1hpaqq1ZZR6pBD1+kI7O24PhDvNGNodjS3MdcEqyrahCp8zbtpv+2B/krUnSmUH80lbAS7MrdeK5IylgKg==";
      };
    };
    "he-1.1.1" = {
      name = "he";
      packageName = "he";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.1.1.tgz";
        sha1 = "93410fd21b009735151f8868c2f271f3427e23fd";
      };
    };
    "http-proxy-1.17.0" = {
      name = "http-proxy";
      packageName = "http-proxy";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy/-/http-proxy-1.17.0.tgz";
        sha512 = "Taqn+3nNvYRfJ3bGvKfBSRwy1v6eePlm3oc/aWVxZp57DQr5Eq3xhKJi7Z4hZpS8PC3H4qI+Yly5EmFacGuA/g==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "opener-1.4.3" = {
      name = "opener";
      packageName = "opener";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/opener/-/opener-1.4.3.tgz";
        sha1 = "5c6da2c5d7e5831e8ffa3964950f8d6674ac90b8";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "portfinder-1.0.13" = {
      name = "portfinder";
      packageName = "portfinder";
      version = "1.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/portfinder/-/portfinder-1.0.13.tgz";
        sha1 = "bb32ecd87c27104ae6ee44b5a3ccbf0ebb1aede9";
      };
    };
    "qs-2.3.3" = {
      name = "qs";
      packageName = "qs";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-2.3.3.tgz";
        sha1 = "e9e85adbe75da0bbe4c8e0476a086290f863b404";
      };
    };
    "requires-port-1.0.0" = {
      name = "requires-port";
      packageName = "requires-port";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz";
        sha1 = "925d2601d39ac485e091cf0da5c6e694dc3dcaff";
      };
    };
    "union-0.4.6" = {
      name = "union";
      packageName = "union";
      version = "0.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/union/-/union-0.4.6.tgz";
        sha1 = "198fbdaeba254e788b0efcb630bc11f24a2959e0";
      };
    };
    "url-join-2.0.5" = {
      name = "url-join";
      packageName = "url-join";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-join/-/url-join-2.0.5.tgz";
        sha1 = "5af22f18c052a000a48d7b82c5e9c2e2feeda728";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
  };
  args = {
    name = "http-server";
    packageName = "http-server";
    version = "0.11.1";
    src = ./.;
    dependencies = [
      sources."async-1.5.2"
      sources."colors-1.0.3"
      sources."corser-2.0.1"
      sources."debug-3.1.0"
      sources."ecstatic-3.2.1"
      sources."eventemitter3-3.1.0"
      sources."follow-redirects-1.5.1"
      sources."he-1.1.1"
      sources."http-proxy-1.17.0"
      sources."mime-1.6.0"
      sources."minimist-1.2.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."ms-2.0.0"
      sources."opener-1.4.3"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
        ];
      })
      (sources."portfinder-1.0.13" // {
        dependencies = [
          sources."debug-2.6.9"
        ];
      })
      sources."qs-2.3.3"
      sources."requires-port-1.0.0"
      sources."union-0.4.6"
      sources."url-join-2.0.5"
      sources."wordwrap-0.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A simple zero-configuration command-line http server";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}